**Membaca Dataset dengan Pandas**

In [ ]:
import numpy as np

nilai = np.array([170, 165, 150, 145])

mean_val = np.mean(nilai)
minmax_val = [np.min(nilai), np.max(nilai)]
median_val = np.median(nilai)
std_val = np.std(nilai)

print("Array      :", nilai)
print("Mean       :", mean_val)
print("MinMax     :", minmax_val)
print("Median     :", median_val)
print("Std        :", std_val)

Array      : [170 165 150 145]
Mean       : 157.5
MinMax     : [np.int64(145), np.int64(170)]
Median     : 157.5
Std        : 10.307764064044152

**Eksplorasi Awal Dataset**

In [ ]:
import pandas as pd
url = "https://raw.githubusercontent.com/mwaskom/seaborn-data/master/titanic.csv"

df = pd.read_csv(url)
df.head() # menampilkan 5 baris pertama

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

**Mengakses dan Memfilter Data**

In [ ]:
print(df.shape)
print(df.columns)

df.info()

df.describe()

(891, 15)
Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town',
       'alive', 'alone'],
      dtype='object')
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    object
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    object
 8   class        891 non-null    object
 9   who          891 non-null    object
 10  adult_male   891 non-null    bool
 11  deck         203 non-null    object
 12  embark_town  889 non-null    object
 13  alive        891 non-null    object
 14  alone        891 non-null    bool
dtypes: bool(2), float64(2), int64(4), object(7)
memory usage: 92.4+ KB

         survived      pclass         age       sibsp       parch        fare
count  891.000000  891.000000  714.000000  891.000000  891.000000  891.000000
mean     0.383838    2.308642   29.699118    0.523008    0.381594   32.204208
std      0.486592    0.836071   14.526497    1.102743    0.806057   49.693429
min      0.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%      0.000000    2.000000   20.125000    0.000000    0.000000    7.910400
50%      0.000000    3.000000   28.000000    0.000000    0.000000   14.454200
75%      1.000000    3.000000   38.000000    1.000000    0.000000   31.000000
max      1.000000    3.000000   80.000000    8.000000    6.000000  512.329200

**Mendeteksi Missing Value**

In [ ]:
# Mengakses satu kolom
df["age"].head()

# Mengakses beberapa kolom sekaligus
df[["age"
,
"sex"
,
"survived"]].head()

# Memfilter baris berdasarkan kondisi (boolean indexing)
penumpang_anak = df[df["age"] < 18]
print("Jumlah penumpang anak:"

, len(penumpang_anak))

Jumlah penumpang anak: 113

In [ ]:
print(df.isnull().sum())

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

**Menangani Missing Value**

In [ ]:
df["age"] = df["age"].fillna(df["age"].mean())

In [ ]:
df = df.dropna(subset=["embarked"])

**Mendeteksi dan Menghapus Duplikasi**

In [ ]:
print("Sebelum:" , len(df))

Sebelum: 889

In [ ]:
print("Duplikasi:" , df.duplicated().sum())

df = df.drop_duplicates()

print("Sesudah:", len(df))

Duplikasi: 107
Sesudah: 782

**LATIHAN**

In [ ]:
# Latihan: bandingkan usia rata-rata NumPy vs Pandas
import numpy as np
import pandas as pd

url = "https://raw.githubusercontent.com/mwaskom/seaborn-data/master/titanic.csv"
df = pd.read_csv(url)

rata_numpy = np.mean(df["age"].dropna())
rata_pandas = df["age"].mean()

print("NumPy :" , rata_numpy)

print("Pandas:" , rata_pandas)

NumPy : 29.69911764705882
Pandas: 29.69911764705882

**Filter data penumpang kelas 1 yang selamat dan mengisi missing value**

In [ ]:
# Filter data penumpang kelas 1 yang selamat
df_filtered = df[(df['pclass'] == 1) & (df['survived'] == 1)]

# Menampilkan 5 data teratas dari hasil filter
print("Data penumpang kelas 1 yang selamat:")
print(df_filtered.head())
print("-" * 30)

# Isi missing value kolom 'embarked' dengan modusnya
print("Missing value 'embarked' sebelum:", df['embarked'].isna().sum())

# Mengisi missing value dengan modus
modus_embarked = df['embarked'].mode()[0]
df['embarked'] = df['embarked'].fillna(modus_embarked)

# Cek jumlah missing value setelah diisi
print("Missing value 'embarked' sesudah:", df['embarked'].isna().sum())

Data penumpang kelas 1 yang selamat:
    survived  pclass     sex   age  sibsp  parch      fare embarked  class  \
1          1       1  female  38.0      1      0   71.2833        C  First
3          1       1  female  35.0      1      0   53.1000        S  First
11         1       1  female  58.0      0      0   26.5500        S  First
23         1       1    male  28.0      0      0   35.5000        S  First
31         1       1  female   NaN      1      0  146.5208        C  First

      who  adult_male deck  embark_town alive  alone
1   woman       False    C    Cherbourg   yes  False
3   woman       False    C  Southampton   yes  False
11  woman       False    C  Southampton   yes   True
23    man        True    A  Southampton   yes   True
31  woman       False    B    Cherbourg   yes  False
------------------------------
Missing value 'embarked' sebelum: 2
Missing value 'embarked' sesudah: 0

# PRAKTIKUM MODUL PERTEMUAN 3

**Menyiapkan Notebook dan Mengimpor Library**

In [ ]:
import numpy as np
import pandas as pd

**Dasar Array NumPy**

In [ ]:
# Membuat array NumPy dari sebuah list
nilai_ujian = np.array([78, 85, 90, 65, 72])
print("Rata-rata:", np.mean(nilai_ujian))
print("Maksimum:", np.max(nilai_ujian))
print("Minimum:", np.min(nilai_ujian))
print("Std Deviasi:", np.std(nilai_ujian))

Rata-rata: 78.0
Maksimum: 90
Minimum: 65
Std Deviasi: 8.921883209278185

**Membaca Dataset dengan Pandas**

In [ ]:
url = "https://raw.githubusercontent.com/mwaskom/seaborn-data/master/titanic.csv"
df = pd.read_csv(url)
df.head() # menampilkan 5 baris pertama

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

**Eksplorasi Awal Dataset**

In [ ]:
print(df.shape) # jumlah baris & kolom
print(df.columns) # nama-nama kolom
df.info() # tipe data & jumlah data tidak kosong
df.describe() # statistik deskriptif kolom numerik

(891, 15)
Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town',
       'alive', 'alone'],
      dtype='object')
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    object
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    object
 8   class        891 non-null    object
 9   who          891 non-null    object
 10  adult_male   891 non-null    bool
 11  deck         203 non-null    object
 12  embark_town  889 non-null    object
 13  alive        891 non-null    object
 14  alone        891 non-null    bool
dtypes: bool(2), float64(2), int64(4), object(7)
memory usage: 92.4+ KB

         survived      pclass         age       sibsp       parch        fare
count  891.000000  891.000000  714.000000  891.000000  891.000000  891.000000
mean     0.383838    2.308642   29.699118    0.523008    0.381594   32.204208
std      0.486592    0.836071   14.526497    1.102743    0.806057   49.693429
min      0.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%      0.000000    2.000000   20.125000    0.000000    0.000000    7.910400
50%      0.000000    3.000000   28.000000    0.000000    0.000000   14.454200
75%      1.000000    3.000000   38.000000    1.000000    0.000000   31.000000
max      1.000000    3.000000   80.000000    8.000000    6.000000  512.329200

**Mengakses Kolom dan Bari**s

In [ ]:
# Mengakses satu kolom
df["age"].head()
# Mengakses beberapa kolom sekaligus
df[["age", "sex", "survived"]].head()
# Memfilter baris berdasarkan kondisi
penumpang_anak = df[df["age"] < 18]
print("Jumlah penumpang anak:", len(penumpang_anak))

Jumlah penumpang anak: 113

**Mendeteksi Missing Value**

In [ ]:
print(df.isnull().sum())

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

**Menangani Missing Value**

In [ ]:
# Strategi 1: isi nilai kosong dengan rata-rata (untuk data numerik)
df["age"] = df["age"].fillna(df["age"].mean())

# Strategi 2: hapus baris yang datanya kosong pada kolom tertentu
df = df.dropna(subset=["embarked"])

print(df.isnull().sum()) # periksa kembali

survived         0
pclass           0
sex              0
age              0
sibsp            0
parch            0
fare             0
embarked         0
class            0
who              0
adult_male       0
deck           688
embark_town      0
alive            0
alone            0
dtype: int64

**Mendeteksi dan Menghapus Duplikasi**

In [ ]:
print("Jumlah data sebelum:", len(df))
print("Jumlah duplikasi:", df.duplicated().sum())

df = df.drop_duplicates()
print("Jumlah data sesudah:", len(df))

Jumlah data sebelum: 889
Jumlah duplikasi: 107
Jumlah data sesudah: 782

**Menyimpan Dataset yang Sudah Dibersihkan**

In [ ]:
df.to_csv("titanic_bersih.csv", index=False)

# LATIHAN MANDIRI

Latihan 1

In [ ]:
print("10 baris pertama:")
display(df.head(10))

print("\n5 baris terakhir:")
display(df.tail(5))

10 baris pertama:

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.000000,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.000000,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.000000,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.000000,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.000000,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
5,0,3,male,29.699118,0,0,8.4583,Q,Third,man,True,NaN,Queenstown,no,True
6,0,1,male,54.000000,0,0,51.8625,S,First,man,True,E,Southampton,no,True
7,0,3,male,2.000000,3,1,21.0750,S,Third,child,False,NaN,Southampton,no,False
8,1,3,female,27.000000,0,2,11.1333,S,Third,woman,False,NaN,Southampton,yes,False
9,1,2,female,14.000000,1,0,30.0708,C,Second,child,False,NaN,Cherbourg,yes,False

5 baris terakhir:

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
885,0,3,female,39.000000,0,5,29.125,Q,Third,woman,False,NaN,Queenstown,no,False
887,1,1,female,19.000000,0,0,30.000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,29.699118,1,2,23.450,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.000000,0,0,30.000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.000000,0,0,7.750,Q,Third,man,True,NaN,Queenstown,no,True

Latihan 2

In [ ]:
# Hitung rata-rata usia menggunakan NumPy dan Pandas

rata_usia_numpy = np.mean(df['age'])
rata_usia_pandas = df['age'].mean()

print(f"Rata-rata usia menggunakan NumPy: {rata_usia_numpy:.4f}")
print(f"Rata-rata usia menggunakan Pandas: {rata_usia_pandas:.4f}")

if np.isclose(rata_usia_numpy, rata_usia_pandas):
    print("Hasilnya sama.")
else:
    print("Hasilnya berbeda.")

Rata-rata usia menggunakan NumPy: 29.7948
Rata-rata usia menggunakan Pandas: 29.7948
Hasilnya sama.

Latihan 3

In [ ]:
penumpang_kelas_1_selamat = df[(df['pclass'] == 1) & (df['survived'] == 1)]

print("Data penumpang kelas 1 yang selamat:")

display(penumpang_kelas_1_selamat.head())

Data penumpang kelas 1 yang selamat:

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
1,1,1,female,38.000000,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
3,1,1,female,35.000000,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
11,1,1,female,58.000000,0,0,26.5500,S,First,woman,False,C,Southampton,yes,True
23,1,1,male,28.000000,0,0,35.5000,S,First,man,True,A,Southampton,yes,True
31,1,1,female,29.699118,1,0,146.5208,C,First,woman,False,B,Cherbourg,yes,False

Latihan 4

In [ ]:
# Tampilkan jumlah missing value sebelum pengisian
print("Jumlah missing value di 'embarked' sebelum diisi:", df['embarked'].isnull().sum())

# Hitung modus dari kolom 'embarked'
modus_embarked = df['embarked'].mode()[0]

# Isi missing value dengan modus
df['embarked'] = df['embarked'].fillna(modus_embarked)

# Tampilkan jumlah missing value setelah pengisian
print("Jumlah missing value di 'embarked' setelah diisi:", df['embarked'].isnull().sum())

Jumlah missing value di 'embarked' sebelum diisi: 0
Jumlah missing value di 'embarked' setelah diisi: 0

Latihan 5

In [ ]:
persentase_selamat = df['survived'].mean() * 100
print(f"Persentase penumpang yang selamat: {persentase_selamat:.2f}%")

Persentase penumpang yang selamat: 41.05%

## **PERTANYAAN DIKSUSI**

1. Memeriksa dan menangani missing value penting agar visualisasi tidak menyesatkan atau menyebabkan error, sehingga grafik yang dihasilkan dapat menampilkan informasi statistik yang akurat dan dapat dipercaya.

2. Penggunaan dropna() dan fillna() disesuaikan dengan kondisi data:

    a. dropna() digunakan saat jumlah data hilang sangat sedikit atau saat pengisian nilai buatan dapat merusak keaslian data seperti pada ID dan koordinat.

    b. fillna() digunakan saat data hilang cukup banyak agar tidak kehilangan informasi penting, serta terdapat nilai pengganti yang logis seperti rata-rata, nilai tengah, atau nilai nol.

3. Data duplikat yang tidak dihapus memicu risiko bias statistik dan distorsi visualisasi, di mana nilai total, rata-rata, dan proporsi grafik akan tergelembungkan akibat perhitungan ulang pada data yang sama.